=== cfcodefans/MQueueDispatcher/src/test/resources/job.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="tnc" xmlns:ns1="tnc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <xs:import namespace="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="xsixml"/>
    <xs:element name="jobs">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:conf"  maxOccurs="1" />
                <xs:element ref="ns1:monitor"  maxOccurs="1"/>
                <xs:element ref="ns1:servers"  maxOccurs="1"/>
                <xs:element ref="ns1:job" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="conf">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:request-pre"/>
                <xs:element ref="ns1:request-count"/>
                <xs:element ref="ns1:request-timeout"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="request-pre" type="xs:anyURI"/>
    <xs:element name="request-count" type="xs:integer"/>
    <xs:element name="request-timeout" type="xs:integer"/>
    <xs:element name="monitor">
        <xs:complexType>
            <xs:attribute name="httpHost" use="required" type="xs:NCName"/>
            <xs:attribute name="httpPort" use="required" type="xs:integer"/>
            <xs:attribute name="rHost" use="required" type="xs:NCName"/>
            <xs:attribute name="rPort" use="required" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="servers">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="ns1:queueserver"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="queueserver">
        <xs:complexType>
            <xs:attribute name="host" use="required" type="xs:NCName"/>
            <xs:attribute name="logFileName" type="xs:string"/>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
            <xs:attribute name="password" use="required" type="xs:NCName"/>
            <xs:attribute name="port" use="required" type="xs:integer"/>
            <xs:attribute name="redisHost" type="xs:NCName"/>
            <xs:attribute name="redisPort" type="xs:integer"/>
            <xs:attribute name="retryIntervalSeconds" type="xs:integer"/>
            <xs:attribute name="userName" use="required" type="xs:NCName"/>
            <xs:attribute name="vhost" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="job">
        <xs:complexType>
            <xs:attribute name="exchange" use="required" type="xs:NCName"/>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
            <xs:attribute name="retryLimit" use="required" type="xs:integer"/>
            <xs:attribute name="routeKey" use="optional" type="xs:NCName"/>
            <xs:attribute name="server" use="required" type="xs:NCName"/>
            <xs:attribute name="url" use="required" type="xs:anyURI"/>
            <xs:attribute name="exchangeDurable" use="optional" type="xs:boolean"/>
            <xs:attribute name="queueDurable" use="optional" type="xs:boolean"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== cfcodefans/MQueueDispatcher/job.xml
<?xml version="1.0" encoding="UTF-8"?>
<jobs xmlns="tnc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="tnc job.xsd">
  <conf>
    <request-pre>http://develop.poppen.lab/frontend_dev.php/consumerDispatch/dispatch/</request-pre>
    <request-count>1</request-count>
    <request-timeout>30000</request-timeout>
  </conf>
  <monitor rHost="10.60.1.253" rPort="9998" httpHost="10.60.1.253" httpPort="8888"/>
  <servers>
    <queueserver name="a" host="snowball" port="5672" userName="guest" password="guest" vhost="/" logFileName="/var/log/consumerDispatcher/poppen_a.log" redisHost="moleman-poppen" redisPort="6379" /> 
    <queueserver name="b" host="snowball" port="5672" userName="guest" password="guest" vhost="/" logFileName="/var/log/consumerDispatcher/poppen_b.log"/>
    <queueserver name="c" host="snowball" port="5672" userName="fetisch" password="fetisch" vhost="/fetisch" logFileName="/var/log/consumerDispatcher/fetisch_c.log" redisHost="moleman-poppen" redisPort="6379" />
    <queueserver name="e" host="snowball" port="5672" userName="guest" password="guest" vhost="/21407" logFileName="/var/log/consumerDispatcher/poppen_21407.log" />
    <queueserver name="f" host="snowball" port="5672" userName="guest" password="guest" vhost="/22031" logFileName="/var/log/consumerDispatcher/poppen_22031.log" />
    <queueserver name="g" host="snowball" port="5672" userName="kaufmich" password="kaufmich" vhost="/kaufmich" logFileName="/var/log/consumerDispatcher/kaufmich_g.log" />
    <queueserver name="s" host="snowball" port="5672" userName="kaufmich" password="kaufmich" vhost="/" logFileName="/var/log/consumerDispatcher/kaufmich_s.log" />
    <queueserver name="h" host="snowball" port="5672" userName="flirten" password="flirten" vhost="/flirten" logFileName="/var/log/consumerDispatcher/flirten_h.log" />
    <queueserver name="i" host="snowball" port="5672" userName="gays" password="gays" vhost="/gays" logFileName="/var/log/consumerDispatcher/gays_i.log" />
  </servers>

  <!-- POPPEN -->
  <job name="text_mail" server="a" queue="text_mail" exchange="text_mail_router" timeout="20000" url="http://develop.poppen.lab/frontend_dev.php/consumerDispatch/dispatch/"  />
  <job name="update_search_info_in_solr" server="a" exchange="update_search_info_in_solr_router" url="http://develop.poppen.lab/frontend_dev.php/consumerDispatch/dispatch/" />
  <job name="mongo" server="a" exchange="mongo_exchange" url="http://red.xie.poppen.lab/frontend_dev.php/consumerDispatch/dispatch/" />
  <job name="vote_image" server="a"  url="http://red.simon.poppen.lab/frontend_dev.php/consumerDispatch/dispatch"/>
  <job name="tnc_message_system" server="a" url="http://red.xie.poppen.lab/frontend_dev.php/consumerDispatch/dispatch"  />
  <job name="tnc_message_attach_images" server="a" url="http://develop.poppen.lab/frontend_dev.php/consumerDispatch/dispatch"  />
  <job name="videochat_blackword_report" exchange="videochat_blackword_report_router" server="a" url="http://develop.poppen.lab/frontend_dev.php/consumerDispatch/dispatch" />
  <job name="wio_presence_poppen" server="a" queue="wio_presence_poppen" type="topic"  exchange="wio_presence_poppen_exchange" url="http://atkins:8282/wio/rest/queue/consume" />
  <job name="tnc_message_greet_dispatch" exchange="tnc_message_greet_dispatch_router" server="a" url="http://red.xie.poppen.lab/frontend_dev.php/consumerDispatch/dispatch" />
  <job name="iplog_messages" server="c" queue="iplog" exchange="login_queries_router" type="fanout" url="http://develop.fetisch.de.lab/frontend_dev.php/consumerDispatch/dispatch/"/>
  <job name="backend_mail_notification" server="c" url="http://develop.fetisch.de.lab/frontend_dev.php/consumerDispatch/dispatch/" />
  <job name="campaign_system" server="c" queue="campaign_hits" exchange="campaign_router" url="http://develop.fetisch.de.lab/frontend_dev.php/consumerDispatch/dispatch/"/>
  <job name="daily_mail_notification" server="c" url="http://develop.fetisch.de.lab/frontend_dev.php/consumerDispatch/dispatch/" />
  <job name="delete_profile" server="c" url="http://develop.fetisch.de.lab/frontend_dev.php/consumerDispatch/dispatch/" />
  <job name="failed_notification" server="c" url="http://develop.fetisch.de.lab/frontend_dev.php/consumerDispatch/dispatch/" />
  <job name="fast_mail_notification" server="c" url="http://develop.fetisch.de.lab/frontend_dev.php/consumerDispatch/dispatch/" />
  <job name="image_processing" server="c" queue="image_processing_queue" exchange="image_processing_exchange" url="http://develop.fetisch.de.lab/frontend_dev.php/consumerDispatch/dispatch/" retryLimit="10" />
  <job name="login_queries" server="c" type="fanout" url="http://develop.fetisch.de.lab/frontend_dev.php/consumerDispatch/dispatch/"/>
  <job name="message_attach_images" server="c" url="http://develop.fetisch.de.lab/frontend_dev.php/consumerDispatch/dispatch/"/>
  <job name="payment" server="c" url="http://develop.fetisch.de.lab/frontend_dev.php/consumerDispatch/dispatch/" />
  <job name="send_sms" server="c" url="http://develop.fetisch.de.lab/frontend_dev.php/consumerDispatch/dispatch/" />
  <job name="slow_mail_notification" server="c" url="http://develop.fetisch.de.lab/frontend_dev.php/consumerDispatch/dispatch/" />
  <job name="system_messages" server="c" queue="msgs" exchange="router" url="http://develop.fetisch.de.lab/frontend_dev.php/consumerDispatch/dispatch/" />
  <job name="text_mail" server="c" url="http://develop.fetisch.de.lab/frontend_dev.php/consumerDispatch/dispatch/" />
  <job name="unread_archive_msg_counter" server="c" url="http://develop.fetisch.de.lab/frontend_dev.php/consumerDispatch/dispatch/" />
  <job name="create_thumbnails" exchange="create_thumbnails_exchange" server="c" url="http://develop.fetisch.de.lab/frontend_dev.php/consumerDispatch/dispatch/" />
  <job name="top_list" server="c" url="http://develop.fetisch.de.lab/frontend_dev.php/consumerDispatch/dispatch/" />
  <job name="betachat" server="c" url="http://develop.fetisch.de.lab/frontend_dev.php/consumerDispatch/dispatch/" />
  <job name="mongo" exchange="mongo_exchange" server="c" url="http://develop.fetisch.de.lab/frontend_dev.php/consumerDispatch/dispatch/" />
  <job name="session_update" server="c" url="http://develop.fetisch.de.lab/frontend_dev.php/consumerDispatch/dispatch/" />
  <job name="wio_update" server="c" url="http://develop.fetisch.de.lab/frontend_dev.php/consumerDispatch/dispatch/" />
  <job name="update_mongo_misc_data" exchange="update_mongo_misc_data_exchange" server="c" url="http://develop.fetisch.de.lab/frontend_dev.php/consumerDispatch/dispatch/" />
  <job name="tnc_message_attach_images" server="c" url="http://develop.fetisch.de.lab/frontend_dev.php/consumerDispatch/dispatch/" />
  <job name="text_mail" server="e" queue="text_mail" exchange="text_mail_router" url="http://21407.poppen.lab/frontend_dev.php/consumerDispatch/dispatch/"/>
  <job name="update_search_info_in_solr" server="e" exchange="update_search_info_in_solr_router" url="http://21407.poppen.lab/frontend_dev.php/consumerDispatch/dispatch/"/>
  <job name="rate_image" server="e" url="http://21407.poppen.lab/frontend_dev.php/consumerDispatch/dispatch/"/>
  <job name="rate_video" server="e" url="http://21407.poppen.lab/frontend_dev.php/consumerDispatch/dispatch/"/>
  <job name="rate_message" server="e" url="http://21407.poppen.lab/frontend_dev.php/consumerDispatch/dispatch/"/>
  <job name="update_login_status" server="e" url="http://21407.poppen.lab/frontend_dev.php/consumerDispatch/dispatch/"/>
  <job name="update_message_counter" server="e" url="http://21407.poppen.lab/frontend_dev.php/consumerDispatch/dispatch/"/>
  <job name="update_guestbook_counter" server="e" url="http://21407.poppen.lab/frontend_dev.php/consumerDispatch/dispatch/"/>
  <job name="update_sms_counter" server="e" url="http://21407.poppen.lab/frontend_dev.php/consumerDispatch/dispatch/"/>
  <job name="update_new_poke_counter" server="e" url="http://21407.poppen.lab/frontend_dev.php/consumerDispatch/dispatch/"/>
  <job name="reset_new_received_counter" server="e" url="http://21407.poppen.lab/frontend_dev.php/consumerDispatch/dispatch/"/>
  <job name="create_thumbnails" exchange="create_thumbnails_exchange" server="e" url="http://21407.poppen.lab/frontend_dev.php/consumerDispatch/dispatch/"/>
  <job name="top_list" server="e" url="http://21407.poppen.lab/frontend_dev.php/consumerDispatch/dispatch/"/>
  <job name="bounce_mail" server="e" url="http://21407.poppen.lab/frontend_dev.php/consumerDispatch/dispatch/"/>
  <job name="payment" server="e" url="http://21407.poppen.lab/frontend_dev.php/consumerDispatch/dispatch/"/>
  <job name="login_queries" server="e" type="fanout" url="http://21407.poppen.lab/frontend_dev.php/consumerDispatch/dispatch/"/>
  <job name="campaign_system" server="e" queue="campaign_hits" exchange="campaign_router" url="http://21407.poppen.lab/frontend_dev.php/consumerDispatch/dispatch/"/>
  <job name="backend_mail_notification" server="e" retryLimit="500" url="http://21407.poppen.lab/frontend_dev.php/consumerDispatch/dispatch/"/>
  <job name="forum_user_profile_images" server="e" exchange="forum_user_profile_images_exchange" type="fanout" url="http://21407.poppen.lab/frontend_dev.php/consumerDispatch/dispatch/"/>
  <job name="iplog_messages" server="e" queue="iplog" exchange="login_queries_router" type="fanout" url="http://21407.poppen.lab/frontend_dev.php/consumerDispatch/dispatch/"/>
  <job name="failed_notification" server="e" url="http://21407.poppen.lab/frontend_dev.php/consumerDispatch/dispatch/"/>
  <job name="image_processing" server="e" queue="image_processing_queue" exchange="image_processing_exchange" url="http://21407.poppen.lab/frontend_dev.php/consumerDispatch/dispatch/"/>
  <job name="fast_mail_notification" server="e" url="http://21407.poppen.lab/frontend_dev.php/consumerDispatch/dispatch/"/>
